### ISSUE TITLE
BIOS assign memory region for secure OS and normal OS

### ISSUE THREAD

**Issue by Kailiangying** [linaro-swg/bios_qemu_tz_arm#7]
Hi, 

If I understand correctly, bios_qemu_tz_arm should assign physical memory region for secure OS(i.e optee). I do see the configuration file to assign the OPTEE OS memory region at 
https://github.com/linaro-swg/bios_qemu_tz_arm/blob/master/bios/platform_config.h
The TZ_RES_MEM_START, TZ_RES_MEM_SIZE is used to define the memory region for OPTEE. 

I am also looking forward to see these configuration values be used in low level ARM assembly that defines the optee OS physical memory region. I saw the platform_config.h is imported by entry.S. But I did not find where the physical memory region is assigned in entry.S. 

Can anyone kindly tell me where I can find ARM assembly which assign the physical memory region for OPTEE OS?

Thanks in advance.

**Comment by jenswikl** [comment]
Those regions are hardcoded, there's no special assembly tricks. The bios_qemu_tz_arm is a quick and dirty way of getting all the different images need to boot into memory on the qemu-virt platform.

**Comment by Kailiangying** [comment]
Thanks for your reply @jenswi-linaro. I am more curious about how physical memory isolation are enforced by OPTEE on qemu-virt, since this is one main security feature of ARM trustzone.

As you mentioned,  the region are hardcoded, do you mean hard coded in qemu-virt board or in OPTEE OS or BIOS_qemu_tz_arm? If is hard coded in OPTEE related projects, can you kindly point me which source code implement the hard coded memory region? 

My more general question is how qemu-virt CPU knows which memory region should belong to OPTEE OS and can not be accessed by Rich OS?

**Comment by jenswikl** [comment]
That's done in `hw/arm/virt.c` `a15memmap` in the QEMU source.

A better object to study TrustZone solutions is otherwise the ARM Juno board and also the Fast Models provided by ARM.

**Comment by yingkailiang** [comment]
Thanks for your suggestion. I did not find a button to close this issue but your reply is quite clear.

**Comment by Kailiangying** [comment]
Thanks for your reply. Your explain is quite clear
